api:
  client:
    id:     "![5LJHTS0EFTWGiw5Nqr7knxFUMMiJszsqcMDt3KLloLSX8qKq3iDMKMTRCH8YaGRl]"
    secret: "![uJXO8Qy8xmtoFKD/ddlRwpYixr2+TSlVXWkdn++OlllimrfUyRv+bneapqI4UfZt]"
    
  system:
    tracing:
      client_id: "![/hfwkbRRjY6UuurWG679dEQKycIlK2/vMJ1URxfYPmAYoPe/bGGOvoTOgfBuqu8LmiEfCrr0NCqM4D+VBb7E47BpOjkgdlgWYCJ/QCXaM1vwVlNi9aAkAD3jj28NIhZ3]"
      client_secret: "![ChfCW3LtWT+VXYAUHRmapF3uDa4UVYwxosD7RAShb2+KAJoiFC+RT8mb3ZFc3DTY0i/DodkUHv4mcf61BLa4J3oETYWewhih5TtrVFzB1E0=]"

sap:
  connection:
    password: "![ACNfKetPrR5fxu/we99sqjjPNFQL++4xyoe0tqIZylQVKtM4myrqFS1DDpyTEBwK]"
    client:
      secret: "![ACNfKetPrR5fxu/we99sqjjPNFQL++4xyoe0tqIZylQVKtM4myrqFS1DDpyTEBwK]"

    