api:
  client:
    id:     "![5LJHTS0EFTWGiw5Nqr7knxFUMMiJszsqcMDt3KLloLSX8qKq3iDMKMTRCH8YaGRl]"
    secret: "![uJXO8Qy8xmtoFKD/ddlRwpYixr2+TSlVXWkdn++OlllimrfUyRv+bneapqI4UfZt]"
    
  system:
    tracing:
      client_id: "![Mi56v0ROhhJAqVJAOT6a+ytPnG8pVdffSDh7tcIevHRr6CAv3DRqO5sqFpkBIK3UAPgSBsbLi/2x/0RsdHXtP9CpgH3KaFvGY5tQvkaKW1jJvABxxi0rfQ0H1MtVYbRO]"
      client_secret: "![VLK+hH/QjVR6y9fDXb7SqLCSqKLP1AwWjSAZhhE9PJquHEU56ty/lctIANoweGIqAvXD8N1ZoyaPFXP4+dUva5qwAral7jEQTSN8p3tXAAs=]"

sap:
  connection:
    password: "![AlftuaihExKlh3rBYJ+jxw==]"
    client:
#      secret: "foWtbCQZlNluz{~bnSUjcB</}eSaiDHpi/yaK9b{"
      secret: "Jr@rhCG(Swu-o6kxeyzWViY~gUnWYtb(RPKEXnUz"
      


    