#%RAML 1.0 DataType
displayName: Address
description: Address Data Type
type: array
items:
  type: object
  properties:
    addressID:
      type: string
      required: false
      example: xx
    tipologia:
      type: string
      required: false
      example: SOLLECITO
    houseNo2:
      type: string
      required: false
      example: xx
    standardFlag:
      type: string
      required: false
      example: xx
    city:
      type: string
      required: false
      example: xx
    district:
      type: string
      required: false
      example: xx
    postalCode:
      type: string
      required: false
      example: xx
    pOBoxPostalCode:
      type: string
      required: false
      example: xx
    pOBox:
      type: string
      required: false
      example: xx
    street:
      type: string
      required: false
      example: xx
    houseNo:
      type: string
      required: false
      example: xx
    building:
      type: string
      required: false
      example: xx
    floor:
      type: string
      required: false
      example: xx
    roomNo:
      type: string
      required: false
      example: xx
    countryID:
      type: string
      required: false
      example: xx
    countryName:
      type: string
      required: false
      example: xx
    region:
      type: string
      required: false
      example: xx
    regionName:
      type: string
      required: false
      example: xx
    timeZone:
      type: string
      required: false
      example: xx
    taxJurisdictionCode:
      type: string
      required: false
      example: xx
    languageID:
      type: string
      required: false
      example: xx
    shortForm:
      type: string
      required: false
      example: xx
    email:
      type: string
      required: false
      example: xx
    nominativo:
      type: string
      required: false
      example: xx
    tipologiaEmail:
      type: string
      required: false
      example: xx
    fineValidInd:
      type: datetime
      required: false
      example: 2023-12-27T12:00:00.000Z
    inizioValidInd:
      type: datetime
      required: false
      example: 2023-12-27T12:00:00.000Z
      