#%RAML 1.0 DataType 
displayName: Asset Matricola
description: Element of Asset Matricola list
type: object
additionalProperties: true
properties:
  Zmatr:
    type: string
    required: false
  Tag:
    type: string
    required: false
  Etich:
    type: string
    required: false
  Ab:
    type: string
    required: false
  Bis:
    type: string
    required: false
  BuPartner:
    type: string
    required: false
  Equnr:
    type: string
    required: false
  Serge:
    type: string
    required: false
  Setnr:
    type: string
    required: false
  Matnr:
    type: string
    required: false
  Bauform:
    type: string
    required: false
