#%RAML 1.0 DataType 
displayName: Create Asset 
description: Request for Asset creation
type: object
additionalProperties: true
properties:
  ALIA_AB__c:
    type: string
    required: true
  ALIA_MATNR__c:
    type: string
    required: true
  ALIA_ZMATR__c:
    type: string
    required: true
  ALIA_ZTAG__c:
    type: string
    required: true
