#%RAML 1.0 DataType
displayName: Business Partner
description: Business Partner Data Type
type: object
additionalProperties: false
properties:
  BillingCity:
    type: string
    required: false
    maxLength: 40
  BillingPostalCode:
    type: string
    required: false
    maxLength: 10
  BillingStreet:
    type: string
    required: false
    maxLength: 60
  BillingStateCode:
    type: string
    required: false
    maxLength: 3
  BillingCountryCode:
    type: string
    required: false
    maxLength: 3
  ALIA_BILLING_REMARK__c:
    type: string
    required: false
    maxLength: 50
    