#%RAML 1.0 DataType
displayName: Contract
description: Common Contract Data Type
type: object
additionalProperties: true
properties:
  ALIA_OLDKEY__c:
    type: string
    required: false
    description: SAP Contract Number
    displayName: Contract Number
    example: "3000000617"
  ALIA_BUKRS__c:
    type: string
    required: false
    description: SAP Company
    displayName: Company
  ALIA_SPARTE__c:
    type: string
    required: false
  ALIA_KOZIF__c:
    type: string
    required: false
  ALIA_GEMFCAT__c:
    type: string
    required: false
  ALIA_VBEZ__c:
    type: string
    required: false
  ALIA_Account__c:
    type: string
    required: false
    description: SAP Account ID
    displayName: Account ID
    example: "3000000617"
  ALIA_BEGRU__c:
    type: string
    required: false
    example: "FI19"
  ALIA_Premise__c:
    type: string
    required: false
  ALIA_Installation__c:
    type: string
    required: false
    example: "4100000002"
  ALIA_ContractAccount__c:
    type: string
    required: false
    description: SAP Contract Account ID
    displayName: Contract Account ID
    example: "200000000773"
  ALIA_EINZDAT__c:
    type: string
    required: false
    description: Move In Date
    displayName: Move In Date
    example: "2022-02-23T00:00:00"    
  ALIA_AUSZDAT__c:
    type: string
    required: false
    description: Move Out Date
    displayName: Move Out Date
    example:  "9999-12-31T00:00:00"
  ALIA_COKEY__c:
    type: string
    required: false
  ALIA_ZZACCODASS__c:
    type: string
    required: false
  ALIA_ZZACDTBLR__c:
    type: string
    required: false
  ALIA_ZZCONFCAT__c:
    type: boolean
    required: false
  ALIA_ABRSPERR__c:
    type: string
    required: false
  ALIA_ShippingPostalCode__c:
    type: string
    required: false
  ALIA_ShippingCity__c:
    type: string
    required: false
  ALIA_InstlnPremise__c:
    type: string
    required: false
  ALIA_OLDKEY_Premise__c:
    type: string
    required: false
  ALIA_OLDKEY_Instl__c:
    type: string
    required: false
  ContractAccountID:
    type: string
    required: false
  ALIA_VREFER__c:
    type: string
    required: false
  ALIA_CorrispettivoFromDate__c:
    type: string | nil
    required: false    
 


