#%RAML 1.0 DataType
displayName: Device Location
description: Common Device Location Type
type: object
additionalProperties: false
properties:
  ALIA_DEVLOC__c:
    type: string
    required: false
    description: SAP generated ID
    displayName: ID
    maxLength: 40
    example: "567480976762400476"
  ALIA_HAUS__c:
    type: string
    required: false
    maxLength: 40
  ALIA_OLDKEY_Adr__c:
    type: string
    required: false
    maxLength: 40
  ALIA_SWERK__c:
    type: string
    required: false
    maxLength: 4
