#%RAML 1.0 DataType
displayName: Estratto Conto Elem
description: Element of Estratto Conto list
type: object
additionalProperties: true
properties:
  contract_account:
    type: string
    required: false
    example: "1"
  business_partner:
    type: string
    required: false
    example: "12345564"
  document_type:
    type: string
    required: false
    example: "3456784"
  notification_amount:
    type: number
    required: false
    example: 12345
  document_number:
    type: string
    required: false
    example: "Nome struttura"
  description:
    type: string
    required: false
    example: "Tipo documento"
  total_amount:
    type: number
    required: false
    example: 12345
  notification_assessment:
    type: string
    required: false
    example: "Descrizione tipo documento"
  status:
    type: string
    required: false
    example: "Descrizione tipo documento"
  release_date:
    type: string
    required: false
    example: "Descrizione tipo documento"
  expiration_date:
    type: string
    required: false
    example: "Descrizione tipo documento"
  reminder:
    type: string
    required: false
    example: "Descrizione tipo documento"
  reminder_date:
    type: string
    required: false
    example: "Descrizione tipo documento"
  legal_fees:
    type: string
    required: false
    example: "Descrizione tipo documento"
  assessment:
    type: string
    required: false
    example: "Descrizione tipo documento"
  assessment_date:
    type: string
    required: false
    example: "Descrizione tipo documento"
  sanctions:
    type: number
    required: false
    example: 12345
  legal_interest:
    type: number
    required: false
    example: 12345
  reminder_fees:
    type: number
    required: false
    example: 12345
