#%RAML 1.0 DataType
displayName: Installation Elem
description: Element of Installation list
type: object
additionalProperties: true
properties:
  aklasse: 
    type: string
    required: true
    description: "Classe calcolo"
    displayName: "Classe calcolo"
    example: "XX"
  installationid: 
    type: string
    required: true
    description: "installationId"
    displayName: "installationId"
    example: "40002345"
  tariftyp: 
    type: string
    required: true
    description: "Cat. tariffa"
    displayName: "Cat. tariffa"
    example: "XX"
  ableinh: 
    type: string
    required: true
    description: "Uta di lettura"
    displayName: "Uta di lettura"
    example: "XX"
  anlart:
    type: string
    required: true
    description: "Tipo impianto"
    displayName: "Tipo impianto"
    example: "XX"
  divisionid:
    type: string
    required: true
    description: "Settore merc."
    displayName: "Settore merc."
    example: "XX"
  begru:
    type: string
    required: true
    description: "Gruppo autor."
    displayName: "Gruppo autor."
    example: "XX"
  premiseid:
    type: string
    required: true
    description: "Punto di utenza"
    displayName: "Punto di utenza"
    example: "XX"
  zzcodragg:
    type: string
    required: true
    description: "Codice Raggruppament"
    displayName: "Codice Raggruppament"
    example: "XX"
  zzcodraggh:
    type: string
    required: true
    description: "Codice Raggruppament"
    displayName: "Codice Raggruppament"
    example: "XX"


