#%RAML 1.0 DataType 
displayName: Lock
description: Common Lock Type
type: object
additionalProperties: true

properties:
  Id:
    type: string
    required: false
    description: Salesforce Auto generated ID
    displayName: ID
    minLength: 18
    maxLength: 18
    example: "567480976762400476"
  ALIA_LOOBJ__c:
    type: string
    required: false
  ALIA_OLDKEY__c:
    type: string
    required: false
    description: SAP ID of Land Register Data
    displayName: Land Register Data SAP ID 
    example: "a0P3O000004HI7QUAW"
  ALIA_OLDKEY_Premise__c:
    type: string
    required: false
    description: SAP ID of Premise
    displayName: Premise SAP ID 
    example: "a0P3O000004HI7QUAW"
  AccountID:
    type: string
    required: false
  ContractAccount:
    type: string
    required: false
  ContractID:
    type: string
    required: false
  ALIA_LOCKR_EndDate__c:
    type: string
    required: false
  ALIA_LOCKR_StartDate__c:
    type: string
    required: false
  ALIA_PROID__c:
    type: string
    required: false
  ALIA_DOCNUM__c:
    type: string
    required: false
  ALIA_LOCKR__c:
    type: string
    required: false
  ALIA_ABRSPERR__c:
    type: string
    required: false
