#%RAML 1.0 DataType 
displayName: Move Container
description: Element of Move Container list
type: object
additionalProperties: true
properties:
  Anlage:
    type: string
    required: false
    example: "3456784"
  Operand:
    type: string
    required: false
    example: "1"
  Oplfdnr:
    type: string
    required: false
    example: "12345564"
  Ab:
    type: string
    required: false
    example: "01012021"
  Contshare:
    type: string
    required: false
    example: "01012021"
  EqunrWste:
    type: string
    required: false
    example: "0123456789"
  NoUnities:
    type: string
    required: false
    example: "0123456789"
  Behaelter:
    type: string
    required: false
    example: "0123456789"
  BehType:
    type: string
    required: false
    example: "0123456789"
