#%RAML 1.0 DataType 
displayName: Operand
description: Common Operand Data Type
type: object
additionalProperties: false

properties:
  Id:
    type: string
    required: false
    description: Salesforce Auto generated ID
    displayName: ID
    minLength: 18
    maxLength: 18
    example: "567480976762400476"
  CaseId:
    type: string
    required: false
    description: Salesforce Auto generated ID
    displayName: ID
    example: "567480976762400476"
  Name:
    type: string
    required: false
    description: Name
    displayName: Name
    example: "a0B3O000002k26n"
  ALIA_Categoria158__c: 
    type: number
    required: false
    description: Flag for Category 158 (0.0 - no)
    displayName: Category 158
    example: 20
  ALIA_GruppoOperando__c:
    type: string
    required: false
    description: Operand group
    displayName: Operand group
    example: "Agevolazioni"
  ALIA_CodiceOperando__c:
    type: string
    required: false
    description: Operand code
    displayName: Operand code
    example: "TRABARAMMI"
  ALIA_Descrizione_Desc_codice_SAP__c:
    type: string
    required: false
    description: Description of SAP code
    displayName: SAP code description
    example: "Agevolazione Baratto amministrativo"
  ALIA_TipoTariffa__c:
    type: string
    required: false
    description: Tax type
    displayName: Tax type
    example: "TABARA"
  ALIA_TipoTariffaDesc__c:
    type: string
    required: false
    description: Description of tax type
    displayName: Tax type description
    example: "Baratto amministrativo"
  ALIA_Date_validity_start_158__c:
    type: string
    required: false
    description: Validity Start Date for Category 158
    displayName: Validity Start Date for Category 158
    example: "20220301"
  Date_validity_start_Common__c:
    type: string
    required: false
    description: Validity Start Date
    displayName: Validity Start Date
    example: "20211215"
  ALIA_Date_validity_end_158__c:
    type: string
    required: false
    description: Validity End Date for Category 158
    displayName: Validity End Date for Category 158
    example: "20211215"
  Date_validity_end_Common__c:
    type: string
    required: false
    description: Validity End Date
    displayName: Validity End Date
  ALIA_GruppoInfoTariffe__c:
    type: string
    required: false
    description: Tax group
    displayName: Tax group
  ALIA_TipoTariffa_Value__c:
    type: string
    required: false
    description: Tax value
    displayName: Tax value
  ALIA_SFDC_Code__c:
    type: string
    required: false
    description: Tax value
    displayName: Tax value
    example: "SFDC_00114"
  Instln_Premise__c:
    type: string
    required: false
    description: Salesforce ID of Installation Premise
    displayName: Installation Premise Salesforce ID 
    example: "a0P3O000004HI7QUAW"
  ALIA_Catalog_of_Common_Operands_Name__c: 
    type: string
    required: false
    description: Common operands name
    displayName: Common operands name
    example: "Agevolazione Baratto amministrativo - Baratto amministrativo"
  ALIA_Status__c:
    type: string
    required: false
    description: Operand status
    displayName: Operand status
    example: "Sync"
  ALIA_Gruppi_Info__c:
    type: string
    required: false
    description: Gruppi Info
    displayName: Gruppi Info
    example: "TS43"
