#%RAML 1.0 DataType
displayName: Phone Number
description: Phone Number Data Type
type: object
additionalProperties: false
properties:
  ALIA_ICOM_TEL_NUMBER__c:
    type: string
    required: false
    maxLength: 30
  ALIA_ICOM_TEL_REMARK__c:
    type: string
    required: false
    maxLength: 50
  ALIA_ICOM_TEL_MOBILE__c:
    type: string
    required: false
    maxLength: 1
  ALIA_ICOM_TEL_TYPE__c:
    type: string
    required: false
    maxLength: 1
