#%RAML 1.0 DataType
displayName: SanctionablePeriodResponse
description: SanctionablePeriodResponse Data Type
type: object
additionalProperties: false

properties:
    
  ALIA_AUSZDAT__c:
    type: string
    required: false
    description: ALIA Date
    displayName: ALIA_AUSDAT__c
    example: "2023-01-02"
    
    
  ALIA_EINZDAT__c:
    type: string
    required: false
    description: ALIA Date
    displayName: ALIA_EINZDAT__c
    example: "2023-01-01"
    
  CheckSanzione:
    type: boolean
    required: false
    description: CheckSanzione
    displayName: CheckSanzione
    example: true
    
    
    
    
    
