#%RAML 1.0 DataType
displayName: Solleciti Avvisi
description: Response for Solleciti Avvisi requests
type: object
additionalProperties: true
properties:
  status:
    type: !include status.raml
    required: false
    description: Status
    displayName: Status
  recordList:
    type: array
    items: !include sollecitiAvvisi_elem.raml
    required: false
    description: List of Solleciti Avvisi
    displayName: List of Solleciti Avvisi
