#%RAML 1.0 DocumentationItem
title: alia-sys-sap documentation

mediaType: application/json
includes:
  - data_types/account.raml
  - data_types/consumer.raml
  - data_types/registryChain.raml
  - data_types/relationship.raml

content: |
    This is a System API to manage Account and Account Contact Relation information from Salesforce.
    It is invoked to synchronize information related to an existing Business Partner in SAP system when the related Account is updated in Salesforce.
    It is also invoked to create a new Business Partner Relatioship in SAP system when a new Account is created in Salesforce.
    It is also invoked to synchronize information related to an existing Business Partner Relationship in SAP when the related Account Contact Relation is updated on Salesforce.
