#%RAML 1.0
title: alia-sys-sap
description: SAP System API.
version: v1
protocols: HTTPS
baseUri: /alia-sys-sap

documentation:
  - !include documentation/alia-sys-sap-doc.raml

mediaType: application/json

uses:
  dataTypeLibrary: data_types/data-types.raml
  commonTraitsLibrary: libraries/exchange_modules/65bd4d67-2cdf-4fcb-a02a-544e6bed919c/common-library/1.0.0/common-library.raml

/businessPartners:
  is: [commonTraitsLibrary.common-error-handler, commonTraitsLibrary.traceable, commonTraitsLibrary.client-id-required]

  post:
    description: POST SAP Account
    displayName: POST Account
    body:
      application/json:
        type: dataTypeLibrary.account
    responses:
      200:
        body:
          application/json:
            type: dataTypeLibrary.account

  /{businessPartnerId}:
    is: [commonTraitsLibrary.common-error-handler, commonTraitsLibrary.traceable, commonTraitsLibrary.client-id-required]
    
    get:
      description: GET SAP Account
      displayName: Get Account
      responses:
        200:
          body:
            application/json:
              type: dataTypeLibrary.account

    patch:
      description: Update SAP Account
      displayName: Update Account
      body:
        application/json:
          type: dataTypeLibrary.account
      responses:
        200:
          body:
            application/json:
              type: dataTypeLibrary.account
    /address:
      patch:
        description: Update SAP Account
        displayName: Update Account
        body:
          application/json:
            type: dataTypeLibrary.account
/relationships:
  is: [commonTraitsLibrary.common-error-handler, commonTraitsLibrary.traceable, commonTraitsLibrary.client-id-required]

  post:
    description: POST SAP Relationship
    displayName: POST Relationship
    body:
      application/json:
        type: dataTypeLibrary.relationship
    responses:
      200:
        body:
          application/json:
            type: dataTypeLibrary.relationship

  /{relationshipId}:
    is: [commonTraitsLibrary.common-error-handler, commonTraitsLibrary.traceable, commonTraitsLibrary.client-id-required]
    
    get:
      description: GET SAP Relationship
      displayName: Get Relationship
      responses:
        200:
          body:
            application/json:
              type: dataTypeLibrary.relationship

    patch:
      description: Update SAP Relationship
      displayName: Update Relationship
      body:
        application/json:
          type: dataTypeLibrary.relationship
      responses:
        200:
          body:
            application/json:
              type: dataTypeLibrary.relationship

/contracts:
  is: [commonTraitsLibrary.common-error-handler, commonTraitsLibrary.traceable, commonTraitsLibrary.client-id-required]

  post:
    description: POST SAP Contract
    displayName: POST Contract
    body:
      application/json:
        type: dataTypeLibrary.contract
    responses:
      200:
        body:
          application/json:
            type: dataTypeLibrary.contract

  /{contractId}:
    is: [commonTraitsLibrary.common-error-handler, commonTraitsLibrary.traceable, commonTraitsLibrary.client-id-required]
    
    patch:
      description: Update SAP Contract
      displayName: Update Contract
      body:
        application/json:
          type: dataTypeLibrary.contract
      responses:
        200:
          body:
            application/json:
              type: dataTypeLibrary.contract
              
    get:
      description: Get SAP Contract
      displayName: Get Contract
      responses:
        200:
          body:
            application/json:
              type: dataTypeLibrary.contract          
              
    /write-off-billing:
        patch:
          description: Update SAP Contract
          displayName: Update Contract
          body:
            application/json:
              type: dataTypeLibrary.write-off-billing
          responses:
            200:
              body:
                application/json:
                  type: dataTypeLibrary.write-off-billing     

  /evasions:
    is: [commonTraitsLibrary.common-error-handler, commonTraitsLibrary.traceable, commonTraitsLibrary.client-id-required]

    post:
      description: POST SAP Contract Evasion
      displayName: POST Contract Evasion
      body:
        application/json:
          type: dataTypeLibrary.contract
      responses:
        200:
          body:
            application/json:
              type: dataTypeLibrary.contract

    /assessments:
      is: [commonTraitsLibrary.common-error-handler, commonTraitsLibrary.traceable, commonTraitsLibrary.client-id-required]

      post:
        description: POST SAP Contract Evasion Assessment
        displayName: POST Contract Evasion Assessment
        body:
          application/json:
            type: dataTypeLibrary.contract
        responses:
          200:
            body:
              application/json:
                type: dataTypeLibrary.contract
  /write-off:
    is: [commonTraitsLibrary.common-error-handler, commonTraitsLibrary.traceable, commonTraitsLibrary.client-id-required]
  
    post:
      description: POST write-off contracts on SAP
      displayName: POST write-off contracts on SAP
      body:
        application/json:
          properties:
            ALIA_OLDKEY__c :
              description: The Id of the contract
              displayName: Id contract
              type: string
              example: "a031j00000RuPNyAAN"
              required: true
            Action:
              description: The SAP action required
              displayName: SAP action required
              type: string
              enum: ["1","2","3","4"]
              required: true
            ALIA_NEW_EINZDAT__c:
              description: New activaction date
              displayName: New activaction date
              type: string
              required: false
            ALIA_NEW_AUSZDAT__c:
              description: New termination date
              displayName: New termination date
              type: string
              required: false
      responses:
          200:
            body:
              application/json:
                  type: dataTypeLibrary.contract

/contractAccounts:
  is: [commonTraitsLibrary.common-error-handler, commonTraitsLibrary.traceable, commonTraitsLibrary.client-id-required]

  post:
    description: POST SAP Contract Account
    displayName: POST Contract Account
    body:
      application/json:
        type: dataTypeLibrary.contractAccount
    responses:
      200:
        body:
          application/json:
            type: dataTypeLibrary.contractAccount

  /{contractAccountId}:
    is: [commonTraitsLibrary.common-error-handler, commonTraitsLibrary.traceable, commonTraitsLibrary.client-id-required]
    
    patch:
      description: Update SAP Contract Account
      displayName: Update Contract Account
      body:
        application/json:
          type: dataTypeLibrary.contractAccount
      responses:
        200:
          body:
            application/json:
              type: dataTypeLibrary.contractAccount
              
    /email:
      patch:
        description: Update SAP Contract Account Email
        displayName: Update Contract Account Email
        body:
          application/json:
            type: dataTypeLibrary.contractAccountEmail
        responses:
          200:
            body:
              application/json:
                type: dataTypeLibrary.contractAccount
      
              
  /sdiIpaCigCup:
    is: [commonTraitsLibrary.common-error-handler, commonTraitsLibrary.traceable, commonTraitsLibrary.client-id-required]
    
    post:
      description: POST SAP sdiIpaCigCup
      displayName: POST sdiIpaCigCup
      body:
        application/json:
          type: dataTypeLibrary.sdiIpaCigCup
      responses:
        200:
          body:
            application/json:
              type: dataTypeLibrary.sdiIpaCigCup
              
  /{contractAccountOldKey}/addresses:
    /{addressType}:
      is: [commonTraitsLibrary.common-error-handler, commonTraitsLibrary.traceable, commonTraitsLibrary.client-id-required]
      get:
        description: GET SAP Address
        displayName: GET Address
        responses:
          200:
            body:
              application/json:
                type: dataTypeLibrary.address    

/operands:
  is: [commonTraitsLibrary.common-error-handler, commonTraitsLibrary.traceable, commonTraitsLibrary.client-id-required]

  post:
    description: Create a list of Operands 
    displayName: Create Operands
    body:
      application/json:
        type: array 
        items: !include data_types/operand.raml
        description: List of operands of Installation Premise
    responses:
      200:
        body:
          application/json:
            type: dataTypeLibrary.operands

  patch:
    description: Update a list of Operands 
    displayName: Update Operands
    body:
      application/json:
        type: array 
        items: !include data_types/operand.raml
        description: List of operands of Installation Premise
    responses:
      200:
        body:
          application/json:
            type: dataTypeLibrary.operands

  get:
    description: Retrieves a list of all Operandi based on Impianto external key put in query parameters
    displayName: Get Operandi By Impianto.OldKey
    queryParameters:
      installationId:
        description: Id of installation
        displayName: Installation ID
        type: string
        example: "4100000003"
        required: true
      historical:
        description: Retrieve all historic operands
        displayName: Historicarl
        type: boolean
        required: false
        default: false
      common:
        description: Includere common operands
        displayName: Common operands
        type: boolean
        required: false
        default: true
      operands:
        description: Comma separated operands
        displayName: List of operands
        type: string
        required: false
    responses:
      200:
        body:
          application/json:
            type: dataTypeLibrary.operands

/connectionObjects:
  is: [commonTraitsLibrary.common-error-handler, commonTraitsLibrary.traceable, commonTraitsLibrary.client-id-required]

  post:
    description: POST SAP ConnObj
    displayName: POST ConnObj
    body:
      application/json:
        type: dataTypeLibrary.installation
    responses:
      200:
        body:
          application/json:
            type: dataTypeLibrary.installation

  /{connectionObjectId}:
    is: [commonTraitsLibrary.common-error-handler, commonTraitsLibrary.traceable, commonTraitsLibrary.client-id-required]

    patch:
      description: PATCH SAP ConnObj
      displayName: PATCH ConnObj
      body:
        application/json:
          type: dataTypeLibrary.installation
      responses:
        200:
          body:
            application/json:
              type: dataTypeLibrary.installation
  get:
    description: Retrieves a list of connection objects related to a given City Code (citycode) and commucode
    displayName: Get Addresses by CityCode and commucode
    queryParameters:
      commucode:
        type: string
        required: false
        description: Chia. com. cir.
        displayName: Chia. com. cir.
        example: "001000001235"
      regiogroup:
        type: string
        required: false
        description: Raggr.str.reg.
        displayName: Raggr.str.reg.
        example: "PO005"
      civico?:
        type: string
        description: Numero civico
        displayName: Numero civico
        example: "25"
      begru:
        type: string
        required: false
        description: Identificativo comune
        displayName: begru
        example: "FI14"
      city:
        type: string
        required: false
        description: citta
        displayName: citta
        example: "Firenze"
      street:
        type: string
        required: false
        description: strada
        displayName: strada
        example: "VIA LEONARDO DA VINCI"
      houseNum2:
        type: string
        required: false
        description: Numero civico tipo 2
        displayName: house num 2
        example: "A"
    responses:
      200:
        body:
          application/json:
            type: dataTypeLibrary.connectionObjects

/premises:
  is: [commonTraitsLibrary.common-error-handler, commonTraitsLibrary.traceable, commonTraitsLibrary.client-id-required]

  post:
    description: POST SAP Premise
    displayName: POST Premise
    body:
      application/json:
        type: dataTypeLibrary.installation
    responses:
      200:
        body:
          application/json:
            type: dataTypeLibrary.installation

  /{premiseId}:
    is: [commonTraitsLibrary.common-error-handler, commonTraitsLibrary.traceable, commonTraitsLibrary.client-id-required]

    patch:
      description: PATCH SAP Premise
      displayName: PATCH Premise
      body:
        application/json:
          type: dataTypeLibrary.installation
      responses:
        200:
          body:
            application/json:
              type: dataTypeLibrary.installation

/installations:
  is: [commonTraitsLibrary.common-error-handler, commonTraitsLibrary.traceable, commonTraitsLibrary.client-id-required]

  post:
    description: POST SAP ConnObj
    displayName: POST ConnObj
    body:
      application/json:
        type: dataTypeLibrary.installation
    responses:
      200:
        body:
          application/json:
            type: dataTypeLibrary.installation
    
  get:
    description: GET SAP Installation
    displayName: GET Installation
    queryParameters:
      PremiseID:
        type: string
        required: false
        description: Id SAP per premise
        displayName: Id SAP per premise
        example: "001000001235"
    responses:
      200:
        body:
          application/json:
            type: dataTypeLibrary.installation

  /{installationId}:
    is: [commonTraitsLibrary.common-error-handler, commonTraitsLibrary.traceable, commonTraitsLibrary.client-id-required]

    patch:
      description: PATCH SAP Installation
      displayName: PATCH Installation
      body:
        application/json:
          type: dataTypeLibrary.installation
      responses:
        200:
          body:
            application/json:
              type: dataTypeLibrary.installation

/landRegisterData:
  is: [commonTraitsLibrary.common-error-handler, commonTraitsLibrary.traceable, commonTraitsLibrary.client-id-required]

  post:
    description: POST a list of Land Register Data 
    displayName: POST Land Register Data
    body:
      application/json:
        type: dataTypeLibrary.landRegisterData[]
    responses:
      200:
        body:
          application/json:
            type: dataTypeLibrary.landRegisterData[]

/locks:
  is: [commonTraitsLibrary.common-error-handler, commonTraitsLibrary.traceable, commonTraitsLibrary.client-id-required]

  post:
    description: Upsert set of Locks on SAP
    displayName: Upsert Locks
    body:
      application/json:
        type: dataTypeLibrary.lock[]
    responses:
      200:
        body:
          application/json:
            type: dataTypeLibrary.lock[]
  get:
    description: Retrieves a list of all locks based on  Contract Account (Vkont) and Account (Gpart) and Contract (Vertrag) external key put in query parameters
    displayName: Get Locks By Impianto.OldKey
    queryParameters:
      contract_account:
        description: SAP ID of Contract Account (ALIA_ContractAccount__c.ALIA_OLDKEY__c)
        displayName: SAP ID key (Vkont)
        type: string
        example: "854914"
        required: true
      business_partner:
        description: The Id of the Business Partner in SAP system (Account.ALIA_OLDKEY__c)
        displayName: SAP BP Ext key (Gpart)
        type: string
        example: "123456"
        required: true
      contract_id:
        description: SAP ID of Contract - Vertrag - (ALIA_Contract__c.ALIA_OLDKEY__c)
        displayName: SAP ID Contract key (Vertrag)
        type: string
        example: "232333"
        required: false 
    responses:
      200:
        body:
          application/json:
            type: dataTypeLibrary.locks

/estrattoConto:
  is: [commonTraitsLibrary.common-error-handler, commonTraitsLibrary.traceable, commonTraitsLibrary.client-id-required]

  get:
    description: Retrieves a list of all Estratto Conto basing on query parameters
    displayName: Get Estratto Conto
    queryParameters:
      business_partner:
        description: SAP key of the BP
        displayName: SAP BP Ext key
        type: string
        example: "854915"
        required: true
      contract_account:
        description: SAP VKONA of Contract Account
        displayName: SAP VKONA key
        type: string
        example: "854915"
        required: true
    responses:
      200:
        body:
          application/json:
            type: dataTypeLibrary.estrattoConto

/sollecitiAvvisi:
  is: [commonTraitsLibrary.common-error-handler, commonTraitsLibrary.traceable, commonTraitsLibrary.client-id-required]

  get:
    description: Retrieves a list of all Solleciti Avvisi basing on query parameters
    displayName: Get Solleciti Avvisi
    queryParameters:
      business_partner:
        description: SAP key of the BP
        displayName: SAP BP Ext key
        type: string
        example: "854915"
        required: true
      contract_account:
        description: SAP VKONA of Contract Account
        displayName: SAP VKONA key
        type: string
        example: "854915"
        required: true
    responses:
      200:
        body:
          application/json:
            type: dataTypeLibrary.sollecitiAvvisi

/pianoRate:
  is: [commonTraitsLibrary.common-error-handler, commonTraitsLibrary.traceable, commonTraitsLibrary.client-id-required]

  get:
    description: Retrieves a list of all Piano Rate basing on query parameters
    displayName: Get Piano Rate
    queryParameters:
      contract_account:
        description: SAP VKONA of Contract Account
        displayName: SAP VKONA key
        type: string
        example: "854915"
        required: true
    responses:
      200:
        body:
          application/json:
            type: dataTypeLibrary.pianoRate

/moveContainer:
  is: [commonTraitsLibrary.common-error-handler, commonTraitsLibrary.traceable, commonTraitsLibrary.client-id-required]

  get:
    description: Retrieves a list of all Move Contanier basing on query parameters
    displayName: Get Move Container
    queryParameters:
      installationId:
        description: Id of installation
        displayName: Installation ID
        type: string | nil
        example: "4100000003"
        required: false
      EqunrWste:
        description: SAP key of Asset
        displayName: Asset Old key
        type: string | nil
        example: "854915"
        required: false        
    responses:
      200:
        body:
          application/json:
            type: dataTypeLibrary.moveContainer

/asset-matricola:
  is: [commonTraitsLibrary.common-error-handler, commonTraitsLibrary.traceable, commonTraitsLibrary.client-id-required]

  get:
    description: Retrieves a list of all Asset Matricola basing on query parameters
    displayName: Get Asset Matricola
    queryParameters:
      matrCode:
        description: Code of the matricola of the assets
        displayName: Matricola code
        type: string | nil
        example: "LL"
        required: false      
      tagCode:
        description: Code of the tag of the assets
        displayName: Tag code
        type: string | nil
        example: "LL"
        required: false
      labelCode:
        description: Code of the label of the assets
        displayName: Label Code
        type: string | nil
        example: "4100000003"
        required: false
    responses:
      200:
        body:
          application/json:
            type: dataTypeLibrary.asset-matricola

/deviceLocations:
  is: [commonTraitsLibrary.common-error-handler, commonTraitsLibrary.traceable, commonTraitsLibrary.client-id-required]

  post:
    description: Create a Device Location 
    displayName: POST Device Location
    body:
      application/json:
        type: dataTypeLibrary.deviceLocation
    responses:
      200:
        body:
          application/json:
            type: dataTypeLibrary.deviceLocation

  get:
    description: Retrieves the devaice location by Connection Object ID
    displayName: Get Device Location
    queryParameters:
      connectionObjectId:
        description: Id of the Connection Object to search the related Device Location
        displayName: Connection Object ID
        type: string
        example: "4100000003"
        required: true
    responses:
      200:
        body:
          application/json:
            type: dataTypeLibrary.deviceLocation

/asset-containers:
  is: [commonTraitsLibrary.common-error-handler, commonTraitsLibrary.traceable, commonTraitsLibrary.client-id-required]

  post:
    description: Create an Asset Container
    displayName: Create Asset Container
    body:
      application/json:
        type: dataTypeLibrary.asset-matricola
    responses:
      200:
        body:
          application/json:
            type: dataTypeLibrary.asset-matricola

/asset-tag:
  is: [commonTraitsLibrary.common-error-handler, commonTraitsLibrary.traceable, commonTraitsLibrary.client-id-required]  
  
  patch:
    description: PATCH Asset Tag Container
    displayName: Update Asset Container
    body:
      application/json:
        type: dataTypeLibrary.asset-tag-update
    responses:
      200:
        body:
          application/json:
            type: dataTypeLibrary.asset-tag-update
            
  post:
    description: Create Asset Container Tag
    displayName: Create Asset Container Tag
    body:
      application/json:
        type: dataTypeLibrary.asset-tag
    responses:
      200:
        body:
          application/json:
            type: dataTypeLibrary.asset-tag        

/premisesForAddress:
  is: [commonTraitsLibrary.common-error-handler, commonTraitsLibrary.traceable, commonTraitsLibrary.client-id-required]

  post:
    description: Retrieves a list of premises related to a given street
    displayName: Get premises by street
    queryParameters:
      foglio: 
        type: string
        required: false
        description: "Zfoglio"
        displayName: "Zfoglio"
        example: "12345"
      particella: 
        type: string
        required: false
        description: "Zpart"
        displayName: "Zpart"
        example: "12345"
      subalterno: 
        type: string
        required: false
        description: "Zsubal"
        displayName: "Zsubal"
        example: "12345"
    body:
      application/json:
        type: object
        properties: 
          connObjIdList:
            type: array
            items: string
            description: List of ConnObjId
            displayName: List of ConnObjId
    responses:
      200:
        body:
          application/json:
            type: dataTypeLibrary.premisesForAddress
            
/stradario:
  is: [commonTraitsLibrary.common-error-handler, commonTraitsLibrary.traceable, commonTraitsLibrary.client-id-required]

  get:
    description: Retrieves a list of addresses related to a given City Code (REGIOGROUP) and ZipCode (optional)
    displayName: Get Addresses by City Code (RegioGroup) and Zipcode
    queryParameters:
      regiogroup:
        description: Regiogroup code of the municipality to search for
        displayName: Regiogroup code key
        type: string
        example: "PT002"
        required: true
      post_code:
        description: The zipcode of the municipality to search for
        displayName: zipcode
        type: string
        example: "00100"
        required: false
      commu_code:
        description: street code
        displayName: street code
        type: string
        example: "00100"
        required: false      
    responses:
      200:
        body:
          application/json:
            type: dataTypeLibrary.addresses
            
/installation-tracciabilita:
  /{installationId}:
    is: [commonTraitsLibrary.common-error-handler, commonTraitsLibrary.traceable, commonTraitsLibrary.client-id-required]
    patch:
      description: PATCH SAP Installation Tracciabilita
      displayName: PATCH Installation Tracciabilita
      body:
        application/json:
          type: dataTypeLibrary.installation
      responses:
        200:
          body:
            application/json:
              type: dataTypeLibrary.installation

/sanctionable-period:
  is: [commonTraitsLibrary.common-error-handler, commonTraitsLibrary.traceable, commonTraitsLibrary.client-id-required]
  
  post:
      description: Set the sanctionable period
      displayName: Sanctionable period
      body:
        application/json:
          type: dataTypeLibrary.sanctionablePeriod
      responses:
        200:
          body:
            application/json:
              type: dataTypeLibrary.sanctionablePeriodResponse


/accounting-transfer:
  is: [commonTraitsLibrary.common-error-handler, commonTraitsLibrary.traceable, commonTraitsLibrary.client-id-required]
  
  post:
      description: create the accounting-transfer
      displayName: accounting-transfer
      body:
        application/json:
          type: dataTypeLibrary.accounting-transfer
      responses:
        200:
          body:
            application/json:
              type: dataTypeLibrary.accounting-transfer
              
/asset:
  is: [commonTraitsLibrary.common-error-handler, commonTraitsLibrary.traceable, commonTraitsLibrary.client-id-required]
  
  post:
    description: POST Create Asset
    displayName: Create Asset
    body:
      application/json:
        type: dataTypeLibrary.asset
    responses:
      200:
        body:
          application/json:
            type: dataTypeLibrary.assetResponse